# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: "3.9.2"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest
          pip install -r requirements.txt;
      - name: Test with Unittest
        env:
          SECRET_KEY: ${{secrets.SECRET_KEY}}

          DEBUG: ${{secrets.DEBUG}}
          DB_NAME: ${{secrets.DB_NAME}}
          DB_HOST: ${{secrets.DB_HOST}}
          DB_ENGINE: ${{secrets.DB_ENGINE}}
          DB_PORT: ${{secrets.DB_PORT}}

        run: |
          python manage.py test
